src/main/java/orders/OrderClassController.java
package orders;

import orders.util.JsfUtil;
import orders.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("orderClassController")
@SessionScoped
public class OrderClassController implements Serializable {

    private OrderClass current;
    private DataModel items = null;
    @EJB
    private orders.OrderClassFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public OrderClassController() {
    }

    public OrderClass getSelected() {
        if (current == null) {
            current = new OrderClass();
            selectedItemIndex = -1;
        }
        return current;
    }

    private OrderClassFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (OrderClass) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new OrderClass();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrderClassCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (OrderClass) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrderClassUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (OrderClass) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrderClassDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public OrderClass getOrderClass(int id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = OrderClass.class)
    public static class OrderClassControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            OrderClassController controller = (OrderClassController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "orderClassController");
            return controller.getOrderClass(getKey(value));
        }

        int getKey(String value) {
            int key;
            key = Integer.parseInt(value);
            return key;
        }

        String getStringKey(int value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof OrderClass) {
                OrderClass o = (OrderClass) object;
                return getStringKey(o.getOrderId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + OrderClass.class.getName());
            }
        }

    }

}

src/main/webapp/orderClass/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateOrderClassTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateOrderClassLabel_orderId}" for="orderId" style="display:none;" />
                    <h:inputHidden id="orderId" value="0" />
                    <h:outputLabel value="#{bundle.CreateOrderClassLabel_magazzino}" for="magazzino" />
                    <h:selectOneMenu id="magazzino" value="#{orderClassController.selected.magazzino}" title="#{bundle.CreateOrderClassTitle_magazzino}" converter="omnifaces.SelectItemsConverter">
                        <f:selectItems value="#{warehouseController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{orderClassController.create}" value="#{bundle.CreateOrderClassSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{orderClassController.prepareList}" value="#{bundle.CreateOrderClassShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateOrderClassIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/orderClass/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditOrderClassTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditOrderClassLabel_orderId}" for="orderId" />
                    <h:inputText id="orderId" value="#{orderClassController.selected.orderId}" title="#{bundle.EditOrderClassTitle_orderId}" />
                    <h:outputLabel value="#{bundle.EditOrderClassLabel_orderDate}" for="orderDate" />
                    <h:inputText id="orderDate" value="#{orderClassController.selected.orderDate}" title="#{bundle.EditOrderClassTitle_orderDate}" />
                    <h:outputLabel value="#{bundle.EditOrderClassLabel_magazzino}" for="magazzino" />
                    <h:selectOneMenu id="magazzino" value="#{orderClassController.selected.magazzino}" title="#{bundle.EditOrderClassTitle_magazzino}" >
                        <f:selectItems value="#{warehouseController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{orderClassController.update}" value="#{bundle.EditOrderClassSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditOrderClassViewLink}"/>
                <br />
                <h:commandLink action="#{orderClassController.prepareList}" value="#{bundle.EditOrderClassShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditOrderClassIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/orderClass/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListOrderClassTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListOrderClassEmpty}" rendered="#{orderClassController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{orderClassController.items.rowCount > 0}">
                    <h:outputText value="#{orderClassController.pagination.pageFirstItem + 1}..#{orderClassController.pagination.pageLastItem + 1}/#{orderClassController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{orderClassController.previous}" value="#{bundle.Previous} #{orderClassController.pagination.pageSize}" rendered="#{orderClassController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{orderClassController.next}" value="#{bundle.Next} #{orderClassController.pagination.pageSize}" rendered="#{orderClassController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{orderClassController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrderClassTitle_orderId}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrderClassTitle_orderDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderDate}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrderClassTitle_magazzino}"/>
                            </f:facet>
                            <h:outputText value="#{item.magazzino}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{orderClassController.prepareView}" value="#{bundle.ListOrderClassViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{orderClassController.prepareEdit}" value="#{bundle.ListOrderClassEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{orderClassController.destroy}" value="#{bundle.ListOrderClassDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{orderClassController.prepareCreate}" value="#{bundle.ListOrderClassCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListOrderClassIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/orderClass/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewOrderClassTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewOrderClassLabel_orderId}"/>
                    <h:outputText value="#{orderClassController.selected.orderId}" title="#{bundle.ViewOrderClassTitle_orderId}"/>
                    <h:outputText value="#{bundle.ViewOrderClassLabel_orderDate}"/>
                    <h:outputText value="#{orderClassController.selected.orderDate}" title="#{bundle.ViewOrderClassTitle_orderDate}"/>
                    <h:outputText value="#{bundle.ViewOrderClassLabel_magazzino}"/>
                    <h:outputText value="#{orderClassController.selected.magazzino}" title="#{bundle.ViewOrderClassTitle_magazzino}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{orderClassController.destroyAndView}" value="#{bundle.ViewOrderClassDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewOrderClassEditLink}"/>
                <br />
                <h:commandLink action="#{orderClassController.prepareCreate}" value="#{bundle.ViewOrderClassCreateLink}" />
                <br />
                <h:commandLink action="#{orderClassController.prepareList}" value="#{bundle.ViewOrderClassShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewOrderClassIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>